Add copyright, bump version to 0.99, check dirs, no manual, install with DESTDIR, fix exits

diff --git a/barcode.SlackBuild b/barcode.SlackBuild
--- a/barcode.SlackBuild
+++ b/barcode.SlackBuild
@@ -1,48 +1,76 @@
 #!/bin/sh
 #
-# SlackBuild for GNU Barcode
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Slackware build script for Barcode
+# Copyright (C) 2007,2013 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+#
+# Visit SlackPack at http://sotirov-bg.net/slackpack/
+#
+# $Id: barcode.SlackBuild,v 1.2 2013/04/20 05:16:53 gsotirov Exp $
 #
 
-. ../slack-package.conf
-
+. ../../slack-package.conf 
 NAME=barcode
-VERSION=0.98
-BUILD=1
+VERSION=0.99
 ARCH=${ARCH:-i486}
+BUILD=${BUILD:-1}
 
 TMP=${TMP:-/tmp}
+CWD=${CWD:-`pwd`}
+PKG_DIR=${PKG_DIR:-/tmp}
 
-cd $TMP
-tar -zxvf $CWD/$NAME-$VERSION.tar.gz
+if [ ! -e $TMP ]; then
+  mkdir -p $TMP # location to build the source
+fi
+
 SRC=$TMP/$NAME-$VERSION
+if [ -e $SRC -a -d $SRC ]; then
+  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  exit 1
+fi
+
+PKG=$TMP/package-$NAME
+if [ -e $PKG -a -d $PKG ]; then
+  echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
+  exit 2
+fi
+mkdir -p $PKG
+
+# Extract the source
+cd $TMP
+tar -xvf $CWD/$NAME-$VERSION.tar.?z* || exit 3
 cd $SRC
 fix_source
 
+# Configure
 CFLAGS=$SLKCFLAGS \
 CXXFLAGS=$SLKCFLAGS \
 ./configure --build=$ARCH-slackware-linux \
             --host=$ARCH-slackware-linux \
             --prefix=/usr \
-            --mandir=/usr/man \
-            --infodir=/usr/info
+            --infodir=/usr/info || exit 4
 
-make || exit 1
+# Build & install
+make -j4 || exit 5
+make DESTDIR=$PKG install || exit 6
 
-PKG="$TMP/package-$NAME"
-mkdir -p $PKG
-BINDIR=$PKG/usr/bin \
-INCDIR=$PKG/usr/include \
-LIBDIR=$PKG/usr/lib \
-MAN1DIR=$PKG/usr/man/man1 \
-MAN3DIR=$PKG/usr/man/man3 \
-INFODIR=$PKG/usr/info \
-make -e install
-
+# Prepare
 bin_perms $PKG
 ( cd $PKG; strip_bin; strip_lib )
 ( cd $SRC; create_docs $PKG $NAME-$VERSION )
-gzip_man $PKG
 gzip_info $PKG
 
 mkdir -p $PKG/install
@@ -52,6 +80,7 @@ mkdir -p $PKG/usr/src/slackbuilds/$NAME-$VERSION
 install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION
 
+# Pack
 PKG_DIR=${PKG_DIR:-/tmp}
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
@@ -60,6 +89,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.tgz > $PKGNAME.tgz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up (optionally)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
